name: GitHub Actions Demo
on: 
push:
    branches:
      - main
    tags:
  pull_request:
jobs:
   lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    name: Verify vendor, licenses, do lint
    env:
      GOPATH: /home/runner/work/${{ github.repository }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ./src/github.com/${{ github.repository }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install dependences
        run: |
          sudo apt-get install -y jq