name: Main CI WorkFlow

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'
    
    - name: Install dependencies
      run: |
        go version
        go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
        go get github.com/gomodule/redigo/redis
        go get github.com/google/btree
    - name: Run build
      run: make build